### PR TITLE
add publisher

### PR DESCRIPTION
**Pull request by rokeyyan**
I added the can rename files after building function

### CODE REVIEW

**Comment by rokeyyan** [comment]
I found a bug, global configuration will somehow be cleared

**Comment by brunocantisano** [comment]
Merged changes

**Comment by brunocantisano** [comment]
removing the author tag from java doc.

**Comment by brunocantisano** [comment]
Hello Yan,

Do you have any knowledge about deploying a Jenkins plugin? I merged your
code, but I don't know why I cannot deploy my plugin anymore. I created an
ssh key and updated the key in github, put user and password inside my
settings.xml file, but it's not working.

Best Regards,
Bruno.

Em Ter, 30 de jan de 2018 05:14, rokeyyan <notifications@github.com>
escreveu:

**Pull request closed without merging**
